name: Run Snowflake Queries from Files

on:
  workflow_dispatch:

jobs:
  run-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download SnowSQL
        run: |
          wget https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.21-linux_x86_64.bash
          bash snowsql-1.2.21-linux_x86_64.bash -y

      - name: Add SnowSQL to PATH
        run: |
          echo "$HOME/.snowsql" >> $GITHUB_PATH

      - name: Run all SQL files from dbscripts
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SF_USERNAME }}
          SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWSQL_ROLE: ${{ secrets.SF_ROLE }}
          SNOWSQL_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SNOWSQL_DATABASE: ${{ secrets.SF_DATABASE }}
          SNOWSQL_SCHEMA: ${{ secrets.SF_SCHEMA }}
        run: |
          for file in ./dbscripts/*.sql; do
            echo "Running $file..."
            snowsql -f "$file" || exit 1
          done
